name: Verify Code Base

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

    permissions:
      contents: read
      pull-requests: read
      checks: write

jobs:
  run-go-tests:
    uses: ./.github/workflows/run-unit-tests.yaml

  run-go-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
        with:
          files: |
            .github/**
            cmd/**
            pkg/**
            go.mod
            go.sum
            Makefile
            **/*.go

      - name: Set up Go environment
        if: ${{ steps.changed-files.outputs.any_modified == 'true' }}
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Go linter
        if: ${{ steps.changed-files.outputs.any_modified == 'true' }}
        run: make go-lint
